# main menu
[[main]]
name = "Internet"
url = "posts/internet"
weight = 1
  
[[main]]
name = "Website"
url = "posts/website"
weight = 2
  
[[main]]
name = "Computer"
url = "posts/computer"
weight = 3


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about"
weight = 2

[[footer]]
name = "Sitemap"
url = "sitemap.xml"
weight = 3

[[footer]]
name = "Elements"
url = "elements"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 7

[[footer]]
name = "Terms Conditions"
url = "terms-conditions"
weight = 8